name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
